# Generated by Django 4.0.7 on 2023-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('active', 'Active')], default='active', max_length=10),
        ),
    ]
