# Generated by Django 4.0.7 on 2023-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
